### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by Enchufadoo** [aulisius/jira-task-helper#1]
Hi, I tried to test it but when hovering over the icon I get 

"error loading issues".

this is the output after a couple of attempts 

![image](https://user-images.githubusercontent.com/1263356/29520451-7cff4e8c-8657-11e7-9570-1eea46e5e0b1.png)

I triple checked all the parameters before login in
url: http://project.atlassian.net -> replaced with project
username: my email
password: my pass

I'm using Windows 7

**Comment by aulisius** [comment]
Huh. Weird.

Try giving the url without the protocol (i.e) project.atlassian.net. Also right now, the code assumes the JIRA server is hosted as HTTPS.

**Comment by Enchufadoo** [comment]
It was that! :) without the protocol it works fine

![image](https://user-images.githubusercontent.com/1263356/29537982-246e93fc-869a-11e7-934e-0ebfc8c68b0a.png)

**Comment by aulisius** [comment]
Yay! Closing the issue.
